name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (e.g., 1.0.0)'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "33.0.0"

      - name: Rename APK
        run: |
          VERSION_NAME=$(echo "${{ github.ref_name }}" | sed 's/^v//')
          if [ -z "$VERSION_NAME" ]; then
            VERSION_NAME="${{ github.event.inputs.version }}"
          fi
          mv ${{ steps.sign_app.outputs.signedReleaseFile }} app/build/outputs/apk/release/Languager-${VERSION_NAME}.apk

      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v4.1.0
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Languager ${{ github.ref_name }}
          body: |
            # Languager ${{ github.ref_name }}
            
            ## What's Changed
            ${{ steps.changelog.outputs.changelog }}
            
            ## Installation
            1. Install LSPosed/EdXposed framework
            2. Install this APK
            3. Enable the module in LSPosed/EdXposed Manager
            4. Reboot your device
            5. Configure app languages in the Languager app
          draft: false
          prerelease: false
          files: |
            app/build/outputs/apk/release/Languager-*.apk
