name: Build Languager apk for LSPosed
on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build APK
        run: bash ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: languager-apk
          path: app/build/outputs/apk/debug/app-debug.apk
